package edu.dominio.empresa;

class LlamarSimplex 
{
	public double generarRecomendacion(Cliente cliente)
	{	
		String problema = realizarCalculos(cliente);
		String nombreArchivo = this.CrearSCV(problema);
		if(cliente.getAhorroAutomatico())
		{
			this.mejorarEficienciaHogar(cliente);
		}
		
		return this.ejecutarSimplex();
	}

	public void mejorarEficienciaHogar(Cliente c)
	{
		// TODO FACU - AutoGenerated method sub. (?
	}

	private double ejecutarSimplex()
	{
		SimplexSolver solver = new SimplexSolver();
		SimplexProblem problema = new SimplexProblem();
		problema.parse(leerContenido("Melipath/problema.csv"));
		return solver.solve(problema);
	}
	
	private String leerContenido(String ruta)
	{
		 Path path = Paths.get(ruta);
		 String contenido = "";
		 try{
		 	contenido = new String(Files.readAllBytes(path), StandardCharsets.UTF_8);
		 }
		 catch (IOException e) {
		 	e.printStackTrace();
		 }
		 return contenido;
	}

	private String realizarCalculos(Cliente c)
	{
		//HACE SUS COSAS y genera String<------
		return problema;
	}

	private String CrearSCV (String problema)
	{
		File archivo = new File("Melipath/problema.csv");
		try {
		FileWriter escritor = new FileWriter(archivo,true);
		escritor.write(problema);
		escritor.close();
		return 
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}	
}